### ISSUE TITLE
后台日志一直报错

### ISSUE THREAD

**Issue by MakiseVon** [xzhuz/halo-theme-xue#103]
2020-11-11 23:51:19.863 ERROR 6 --- [Thread-20] run.halo.app.utils.GithubUtils           : Failed to react with github.

org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/hshanx/halo-theme-hshan
	at org.kohsuke.github.Requester.parse(Requester.java:613) ~[github-api-1.84.jar!/:na]
	at org.kohsuke.github.Requester._to(Requester.java:263) ~[github-api-1.84.jar!/:na]
	at org.kohsuke.github.Requester.to(Requester.java:225) ~[github-api-1.84.jar!/:na]
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:421) ~[github-api-1.84.jar!/:na]
	at run.halo.app.utils.GithubUtils$GithubReleases.run(GithubUtils.java:217) ~[classes!/:1.4.2]
	at java.lang.Thread.run(Thread.java:823) [na:1.8.0_272]
Caused by: java.net.UnknownHostException: api.github.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_272]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_272]
	at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_272]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:284) ~[na:1.8.0_272]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_272]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_272]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_272]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_272]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_272]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_272]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[na:1.8.0_272]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[na:1.8.0_272]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_272]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570) ~[na:1.8.0_272]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[na:1.8.0_272]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_272]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) ~[na:1.8.0_272]
	at org.kohsuke.github.Requester.parse(Requester.java:587) ~[github-api-1.84.jar!/:na]
	... 5 common frames omitted

rt，运行期间就日志重复报以上错误...

**Comment by MakiseVon** [comment]
好像是halo的问题
