### ISSUE TITLE
开启全站 Pjax 后有关 Halo-Comment 的一个报错

### ISSUE THREAD

**Issue by MakiseVon** [xzhuz/halo-theme-xue#107]
首次进入的页面如果是一个带 Halo-Comment 的页面（比如，进入一个带 Halo-Comment 的页面，然后强制刷新），切换到其他页面，再切换至一个带 Halo-Comment 的页面，会报以下错误：

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "halo-comment" has already been used with this registry
    at Module.5a74 (https://cdn.jsdelivr.net/npm/halo-comment@latest/dist/halo-comment.min.js:8:178120)
    at n (https://cdn.jsdelivr.net/npm/halo-comment@latest/dist/halo-comment.min.js:1:110)
    at https://cdn.jsdelivr.net/npm/halo-comment@latest/dist/halo-comment.min.js:1:907
    at https://cdn.jsdelivr.net/npm/halo-comment@latest/dist/halo-comment.min.js:1:922
```

**Comment by MakiseVon** [comment]
补充，报错指向 `entry-wc.js`

```javascript
import './setPublicPath'
import Vue from 'vue'
import wrap from '@vue/web-component-wrapper'

// runtime shared by every component chunk
import 'css-loader/dist/runtime/api.js'
import 'vue-style-loader/lib/addStylesShadow'
import 'vue-loader/lib/runtime/componentNormalizer'

import haloComment from '~root/src/components/Comment.vue?shadow'
// Err 发生在这一行
window.customElements.define('halo-comment', wrap(Vue, haloComment))
```
